stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: excel-form-filler
  REPOSITORY_NAME: ${APPLICATION_NAME}
  CONTAINER_IMAGE: ${AWS_ECR_URL}/${REPOSITORY_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_ECR_SECRET_NAME: ecr-credentials
  K8S_NODEPORT: 30279

build:
  stage: build
  only:
    - master
  before_script:
    # Create repository if needed
    - >
      aws ecr create-repository --repository-name ${REPOSITORY_NAME}
      || echo "Repository might have already existed"
  script:
    - docker build -t ${CONTAINER_IMAGE_TAGGED} .
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  stage: deploy
  only:
    - master
  before_script:
    # Create a secret with ECR credentials for K8s to pull
    # Here, we use apply to update it
    # https://stackoverflow.com/questions/47369351/kubectl-apply-vs-kubectl-create
    - >
      kubectl create secret docker-registry ${K8S_ECR_SECRET_NAME}
      --docker-server=${AWS_ECR_URL}
      --docker-username=AWS
      --docker-password $(aws ecr get-login-password)
      --dry-run=client -o yaml
      | kubectl apply -f -
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      # NAMESPACE provided by GitLab
      namespace: ${K8S_NAMESPACE}
