apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          env:
            - name: S3_BUCKET
              value: jtekt-excel-form-filler
            - name: SMTP_SECURE
              value: "yes"
            # - name: LOKI_URL
            #   value: http://loki.monitoring:3100
            - name: OIDC_JWKS_URI
              # TODO: use K8s DNS
              value: http://10.115.1.100:30416/realms/jtekt/protocol/openid-connect/certs
          envFrom:
            - secretRef:
                name: environment-variables
            - secretRef:
                name: excel-form-filler-env
      #     volumeMounts:
      #       - mountPath: /usr/src/app/config/config.yml
      #         name: ${APPLICATION_NAME}-config
      #         subPath: config.yml
      # volumes:
      #   - name: ${APPLICATION_NAME}-config
      #     configMap:
      #       name: ${APPLICATION_NAME}-config
      imagePullSecrets:
        - name: ${K8S_ECR_SECRET_NAME}

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
    - port: 80
      nodePort: ${K8S_NODEPORT}
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
