apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/src/app/config/config.yml
              name: ${APPLICATION_NAME}-config
              subPath: config.yml
      volumes:
        - name: ${APPLICATION_NAME}-config
          configMap:
            name: ${APPLICATION_NAME}-config
      imagePullSecrets:
        - name: ${K8S_ECR_SECRET_NAME}

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
    - port: 80
      nodePort: ${K8S_NODEPORT}
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
